name: pipre-local

services:
  postgres:
    container_name: dev-db
    ports:
      - "${PORT_DB:-5432}:5432"

  backend:
    container_name: dev-back
    environment:
      - FAST_API_URL=http://ml-ia:8000

  ml-ia:
    container_name: dev-ml-ia

  frontend:
    container_name: dev-front
    environment:
      - VITE_USE_LOCAL_BACKEND=true
      - VITE_LOCAL_BACKEND_URL=http://localhost:${PORT_BACK:-8080}
    build:
      args:
        - VITE_USE_LOCAL_BACKEND=true
        - VITE_LOCAL_BACKEND_URL=http://localhost:${PORT_BACK:-8080}
networks:
  pipre-infra-net:
    internal: false
