name: pipre-application

services:

  postgres:
    image: postgres:16-alpine
    container_name: pipre-database
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-pipre_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pipre_password}
      - POSTGRES_DB=${POSTGRES_DB:-pipre_database}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pipre_user} -d ${POSTGRES_DB:-pipre_database}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pipre-infra-net
    logging: &default-logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ml-ia:
    build: ./data-science
    image: pipre-ml-api
    container_name: pipre-ml-ia
    volumes:
      - ml-models:/app/saved_models
      - ./data-science/data:/app/data
    networks:
      - pipre-infra-net
    logging: *default-logging

  backend:
    build: ./backend
    image: pipre-backend
    container_name: pipre-backend
    ports:
      - ${PORT_BACK:-8080}:8080
    environment:
      - DATABASE_URL=${DATABASE_URL:-jdbc:postgresql://postgres:5432/pipre_database}
      - POSTGRES_USER=${POSTGRES_USER:-pipre_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pipre_password}
      - FAST_API_URL=http://ml-ia:8000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - pipre-infra-net
    logging: *default-logging

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_USE_LOCAL_BACKEND=true
        - VITE_LOCAL_BACKEND_URL=http://localhost:${PORT_BACK:-8080}
    image: pipre-frontend
    container_name: pipre-frontend
    ports:
      - ${PORT_FRONT:-3000}:3000
    environment:
      - VITE_USE_LOCAL_BACKEND=true
      - VITE_LOCAL_BACKEND_URL=http://localhost:${PORT_BACK:-8080}
    logging: *default-logging

networks:
  pipre-infra-net:
    internal: true

volumes:
  ml-models:
