name: dev-app
# Quitar comentarios si no estás en el servidor
services:
  postgres:
    container_name: dev-db
    ports:
      - "5432:5432"

  backend:
    profiles:
      - dev
    container_name: dev-back

  ml-ia:
    container_name: dev-ml-ia
    networks:
    - cloud-network

  frontend:
    container_name: dev-front
# Intercambiar ruta si no estas en el servidor
    environment:
      - REACT_APP_API_URL=http://dev-back.yoshua-cloud.dedyn.io
    build:
      args:
        - REACT_APP_API_URL=http://dev-back.yoshua-cloud.dedyn.io
#    environment:
#      - REACT_APP_API_URL=http://localhost:${PORT_BACK:-8080}
#    build:
#      args:
#        - REACT_APP_API_URL=http://localhost:${PORT_BACK:-8080}
#networks:
#  cloud-network::
#    driver: bridge