name: pipre-application

services:

  postgres:
    image: postgres:16-alpine
    container_name: pipre-database
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-pipre_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pipre_password}
      - POSTGRES_DB=${POSTGRES_DB:-pipre_database}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pipre_user} -d ${POSTGRES_DB:-pipre_database}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pipre-infra-net
    logging: &default-logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  ml-ia:
    build: ./data-science
    image: pipre-ml-api
    container_name: pipre-ml-ia
    volumes:
      - ./data-science/saved_models:/app/saved_models
      - ./data-science/data:/app/data
    networks:
      - pipre-infra-net
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/ready', timeout=4)" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 180s
    logging: *default-logging

  backend:
    build: ./backend
    image: pipre-backend
    container_name: pipre-backend
    ports:
      - "${PORT_BACK:-8080}:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL:-jdbc:postgresql://postgres:5432/pipre_database}
      - POSTGRES_USER=${POSTGRES_USER:-pipre_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pipre_password}
      - FAST_API_URL=${FAST_API_URL:-http://dev-ml-ia:8000}
    depends_on:
      postgres:
        condition: service_healthy
      ml-ia:
        condition: service_healthy
    networks:
      - pipre-infra-net
      - cloud-network
    logging: *default-logging

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=https://pipre-backend.yoshua-cloud.dedyn.io/
    image: pipre-frontend
    container_name: pipre-frontend
    ports:
      - "${PORT_FRONT:-3000}:3000"
    environment:
      - REACT_APP_API_URL=https://pipre-backend.yoshua-cloud.dedyn.io/
    networks:
      - cloud-network
    logging: *default-logging

networks:
  pipre-infra-net:
    internal: true
  cloud-network:
    name: ${CLOUD_NETWORK}
    external: true
