name: pipre-dev-application
# Quitar comentarios si no estás en el servidor
services:
  postgres:
    container_name: pipre-dev-database
    ports:
      - "5432:5432"
  backend:
    profiles:
      - dev
    container_name: pipre-dev-backend
  frontend:
    container_name: pipre-dev-frontend
#    environment:
#      - REACT_APP_API_URL=http://localhost:${PORT_BACK:-8080}
#    build:
#      args:
#        - REACT_APP_API_URL=http://localhost:${PORT_BACK:-8080}
networks:
  database-network:
    internal: false
#  app_network:
#    external: true