import type { EnvironmentConfig } from "../types/Simulador";

const BATLLE_COLORS = {
  primary: "var(--danger)",
  secondary: "var(--accent)",
};

const SPACE_COLORS = {
  primary: "var(--primary)",
  secondary: "var(--accent)",
};

const MAZE_COLORS = {
  primary: "var(--primary)",
  secondary: "var(--accent)",
};

const RACE_COLORS = {
  primary: "var(--accent)",
  secondary: "var(--primary)",
};

export const ENVIRONMENT_CONFIGS: Record<string, EnvironmentConfig> = {
  battle: {
    id: "battle",
    name: "Batalla de Robots",
    description: "Arena de combate. Programa tu robot para derrotar enemigos y esquivar ataques.",
    icon: "sports_kabaddi",
    portSlots: [
      { id: "ps_battle_weapon", name: "Puerto de Arma", label: "Cañón Láser", icon: "bolt", accepts: ["Cañón Láser", "Hacha de Combate"] },
      { id: "ps_battle_shield", name: "Puerto de Defensa", label: "Escudo Energético", icon: "shield", accepts: ["Escudo Energético"] },
      { id: "ps_battle_treads", name: "Puerto de Tracción", label: "Orugas de Combate", icon: "settings_motion_mode", accepts: ["Tracción Oruga"] },
      { id: "ps_battle_radar", name: "Puerto de Radar", label: "Radar Táctico", icon: "radar", accepts: ["Radar Táctico"] },
      { id: "ps_battle_sensor", name: "Puerto Sensor", label: "Sensor Ultrasónico", icon: "sensors", accepts: ["Sensor Ultrasónico"] },
    ],
    blocks: [
      {
        type: "al_iniciar_sistema",
        label: "AL_INICIAR_SISTEMA",
        category: "event",
        params: {},
      },
      {
        type: "al_detectar_obstaculo",
        label: "AL_DETECTAR_ENEMIGO",
        category: "event",
        hardwareRequired: "Sensor Ultrasónico",
        params: {},
      },
      {
        type: "mover_ruedas",
        label: "AVANZAR(30)",
        category: "action",
        hardwareRequired: "Tracción Oruga",
        params: { distancia: "30" },
      },
      {
        type: "rotar_nucleo",
        label: "ROTAR(90)",
        category: "action",
        hardwareRequired: "Tracción Oruga",
        params: { grados: "90" },
      },
      {
        type: "atacar",
        label: "ATACAR(50)",
        category: "action",
        hardwareRequired: "Cañón Láser",
        params: { potencia: "50" },
      },
      {
        type: "defender",
        label: "ACTIVAR_ESCUDO()",
        category: "action",
        hardwareRequired: "Escudo Energético",
        params: {},
      },
      {
        type: "escanear_enemigo",
        label: "ESCANEAR_ENEMIGO()",
        category: "action",
        hardwareRequired: "Radar Táctico",
        params: {},
      },
      {
        type: "retroceder",
        label: "RETROCEDER(30)",
        category: "action",
        hardwareRequired: "Tracción Oruga",
        params: { distancia: "30" },
      },
      {
        type: "golpear",
        label: "GOLPEAR()",
        category: "action",
        hardwareRequired: "Hacha de Combate",
        params: {},
      },
      {
        type: "si_distancia",
        label: "SI (distancia < 10)",
        category: "condition",
        hardwareRequired: "Sensor Ultrasónico",
        params: {},
      },
    ],
    hardware: [
      {
        id: "Hacha de Combate",
        name: "Hacha de Combate",
        icon: "swords",
        color: "var(--accent)",
        bgClass: "bg-accent/20",
        textClass: "text-accent",
        borderClass: "border-accent/30",
        desc: "Golpe cuerpo a cuerpo devastador.",
        blocks: "[GOLPEAR]",
        unlocks: ["golpear"],
      },
      {
        id: "Tracción Oruga",
        name: "Orugas de Combate",
        icon: "settings_motion_mode",
        color: "var(--success)",
        bgClass: "bg-success/20",
        textClass: "text-success",
        borderClass: "border-success/30",
        desc: "Desplazamiento táctico en arena.",
        blocks: "[AVANZAR], [ROTAR], [RETROCEDER]",
        unlocks: ["mover_ruedas", "rotar_nucleo", "retroceder"],
      },
      {
        id: "Cañón Láser",
        name: "Cañón Láser",
        icon: "bolt",
        color: BATLLE_COLORS.primary,
        bgClass: "bg-danger/20",
        textClass: "text-danger",
        borderClass: "border-danger/30",
        desc: "Sistema de ataque de precisión.",
        blocks: "[ATACAR]",
        unlocks: ["atacar"],
      },
      {
        id: "Escudo Energético",
        name: "Escudo Energético",
        icon: "shield",
        color: "var(--primary)",
        bgClass: "bg-primary/20",
        textClass: "text-primary",
        borderClass: "border-primary/30",
        desc: "Campo de fuerza defensivo.",
        blocks: "[ACTIVAR_ESCUDO]",
        unlocks: ["defender"],
      },
      {
        id: "Radar Táctico",
        name: "Radar Táctico",
        icon: "radar",
        color: "var(--accent)",
        bgClass: "bg-accent/20",
        textClass: "text-accent",
        borderClass: "border-accent/30",
        desc: "Detección de unidades enemigas.",
        blocks: "[ESCANEAR_ENEMIGO]",
        unlocks: ["escanear_enemigo"],
      },
      {
        id: "Sensor Ultrasónico",
        name: "Sensor Ultrasónico",
        icon: "sensors",
        color: "var(--primary)",
        bgClass: "bg-primary/20",
        textClass: "text-primary",
        borderClass: "border-primary/30",
        desc: "Sensor de proximidad para maniobras evasivas.",
        blocks: "[SI_DISTANCIA], [AL_DETECTAR_ENEMIGO]",
        unlocks: ["si_distancia", "al_detectar_obstaculo"],
      },
    ],
    missions: [
      { id: "b1", title: "Ensamblaje de Combate", objective: "Equipa las Orugas de Combate y el Cañón Láser.", maxBlocks: 0 },
      { id: "b2", title: "Patrullaje", objective: "Avanza 3 veces hacia la zona enemiga usando [AVANZAR].", maxBlocks: 3 },
      { id: "b3", title: "Ataque Sorpresa", objective: "Avanzar, usar [ATACAR] y retroceder. Máximo 4 bloques.", maxBlocks: 4 },
      { id: "b4", title: "Defensa Activa", objective: "Activa [ESCANEAR_ENEMIGO] y [ACTIVAR_ESCUDO] al detectar amenaza.", maxBlocks: 5 },
      { id: "b5", title: "Asalto Final", objective: "Combina movimiento, ataque y defensa para derrotar al jefe.", maxBlocks: 6 },
    ],
    defaultHardware: ["Tracción Oruga"],
  },

  space: {
    id: "space",
    name: "Exploración Espacial",
    description: "Terreno planetario. Pilota tu módulo de exploración y recolecta muestras.",
    icon: "rocket_launch",
    portSlots: [
      { id: "ps_space_wheels", name: "Puerto de Tracción", label: "Ruedas Lunares", icon: "settings_motion_mode", accepts: ["Ruedas Lunares"] },
      { id: "ps_space_propulsion", name: "Puerto de Propulsión", label: "Propulsores Iónicos", icon: "flight", accepts: ["Propulsores Iónicos"] },
      { id: "ps_space_arm", name: "Puerto de Recolección", label: "Brazo Recolector", icon: "precision_manufacturing", accepts: ["Brazo Recolector", "Taladro Percutor"] },
      { id: "ps_space_analyzer", name: "Puerto de Análisis", label: "Analizador de Suelo", icon: "biotech", accepts: ["Analizador de Suelo"] },
      { id: "ps_space_sensor", name: "Puerto Sensor", label: "Sensor de Proximidad", icon: "sensors", accepts: ["Sensor Ultrasónico"] },
    ],
    blocks: [
      {
        type: "al_iniciar_sistema",
        label: "AL_INICIAR_SISTEMA",
        category: "event",
        params: {},
      },
      {
        type: "mover_ruedas",
        label: "DESPLAZARSE(30)",
        category: "action",
        hardwareRequired: "Ruedas Lunares",
        params: { distancia: "30" },
      },
      {
        type: "rotar_nucleo",
        label: "GIRAR(90)",
        category: "action",
        hardwareRequired: "Ruedas Lunares",
        params: { grados: "90" },
      },
      {
        type: "despegar",
        label: "DESPEGAR(50)",
        category: "action",
        hardwareRequired: "Propulsores Iónicos",
        params: { altura: "50" },
      },
      {
        type: "aterrizar",
        label: "ATERRIZAR()",
        category: "action",
        hardwareRequired: "Propulsores Iónicos",
        params: {},
      },
      {
        type: "recolectar",
        label: "RECOLECTAR_MUESTRA()",
        category: "action",
        hardwareRequired: "Brazo Recolector",
        params: {},
      },
      {
        type: "analizar",
        label: "ANALIZAR_TERRENO()",
        category: "action",
        hardwareRequired: "Analizador de Suelo",
        params: {},
      },
      {
        type: "perforar",
        label: "PERFORAR()",
        category: "action",
        hardwareRequired: "Taladro Percutor",
        params: {},
      },
      {
        type: "si_distancia",
        label: "SI (distancia < 15)",
        category: "condition",
        hardwareRequired: "Sensor Ultrasónico",
        params: {},
      },
    ],
    hardware: [
      {
        id: "Taladro Percutor",
        name: "Taladro Percutor",
        icon: "hardware",
        color: "var(--danger)",
        bgClass: "bg-danger/20",
        textClass: "text-danger",
        borderClass: "border-danger/30",
        desc: "Perfora roca profunda para obtener muestras.",
        blocks: "[PERFORAR]",
        unlocks: ["perforar"],
      },
      {
        id: "Ruedas Lunares",
        name: "Ruedas Lunares",
        icon: "settings_motion_mode",
        color: "var(--success)",
        bgClass: "bg-success/20",
        textClass: "text-success",
        borderClass: "border-success/30",
        desc: "Tracción para superficie planetaria.",
        blocks: "[DESPLAZARSE], [GIRAR]",
        unlocks: ["mover_ruedas", "rotar_nucleo"],
      },
      {
        id: "Propulsores Iónicos",
        name: "Propulsores Iónicos",
        icon: "flight",
        color: SPACE_COLORS.primary,
        bgClass: "bg-primary/20",
        textClass: "text-primary",
        borderClass: "border-primary/30",
        desc: "Sistema de vuelo atmosférico.",
        blocks: "[DESPEGAR], [ATERRIZAR]",
        unlocks: ["despegar", "aterrizar"],
      },
      {
        id: "Brazo Recolector",
        name: "Brazo Recolector",
        icon: "precision_manufacturing",
        color: "var(--accent)",
        bgClass: "bg-accent/20",
        textClass: "text-accent",
        borderClass: "border-accent/30",
        desc: "Manipulador de muestras geológicas.",
        blocks: "[RECOLECTAR_MUESTRA]",
        unlocks: ["recolectar"],
      },
      {
        id: "Analizador de Suelo",
        name: "Analizador de Suelo",
        icon: "biotech",
        color: "var(--primary)",
        bgClass: "bg-primary/20",
        textClass: "text-primary",
        borderClass: "border-primary/30",
        desc: "Escáner de composición del terreno.",
        blocks: "[ANALIZAR_TERRENO]",
        unlocks: ["analizar"],
      },
      {
        id: "Sensor Ultrasónico",
        name: "Sensor de Proximidad",
        icon: "sensors",
        color: "var(--accent)",
        bgClass: "bg-accent/20",
        textClass: "text-accent",
        borderClass: "border-accent/30",
        desc: "Evita obstáculos en terreno hostil.",
        blocks: "[SI_DISTANCIA]",
        unlocks: ["si_distancia"],
      },
    ],
    missions: [
      { id: "s1", title: "Aterrizaje", objective: "Equipa Ruedas Lunares y Propulsores. Despega y aterriza.", maxBlocks: 0 },
      { id: "s2", title: "Reconocimiento", objective: "Desplázate 2 veces hacia el cráter usando [DESPLAZARSE].", maxBlocks: 2 },
      { id: "s3", title: "Recolección", objective: "Avance, use [RECOLECTAR_MUESTRA] en zona de interés.", maxBlocks: 3 },
      { id: "s4", title: "Análisis Remoto", objective: "Usa [ANALIZAR_TERRENO] y [SI_DISTANCIA] para evadir obstáculos.", maxBlocks: 4 },
      { id: "s5", title: "Regreso a Base", objective: "Navega el terreno, recolecta 2 muestras y regresa a la base.", maxBlocks: 6 },
    ],
    defaultHardware: ["Ruedas Lunares"],
  },

  maze: {
    id: "maze",
    name: "Laberinto Mágico",
    description: "Recinto encantado. Ilumina el camino, abre puertas y encuentra la salida.",
    icon: "auto_awesome",
    portSlots: [
      { id: "ps_maze_boots", name: "Puerto de Movimiento", label: "Botas de Velocidad", icon: "directions_run", accepts: ["Botas de Velocidad"] },
      { id: "ps_maze_lantern", name: "Puerto de Luz", label: "Faro Mágico", icon: "highlight", accepts: ["Faro Mágico"] },
      { id: "ps_maze_key", name: "Puerto de Llave", label: "Llave Antigua", icon: "vpn_key", accepts: ["Llave Antigua"] },
      { id: "ps_maze_mirror", name: "Puerto de Visión", label: "Espejo de Visión", icon: "visibility", accepts: ["Espejo de Visión"] },
      { id: "ps_maze_portal", name: "Puerto Portal", label: "Portal de Teletransporte", icon: "swipe", accepts: ["Portal de Teletransporte"] },
      { id: "ps_maze_sensor", name: "Puerto Sensor", label: "Sensor Mágico", icon: "sensors", accepts: ["Sensor Ultrasónico"] },
      { id: "ps_maze_ice", name: "Puerto de Hielo", label: "Cristal de Escarcha", icon: "ac_unit", accepts: ["Cristal de Escarcha"] },
    ],
    blocks: [
      {
        type: "al_iniciar_sistema",
        label: "AL_INICIAR_SISTEMA",
        category: "event",
        params: {},
      },
      {
        type: "mover_ruedas",
        label: "AVANZAR(20)",
        category: "action",
        hardwareRequired: "Botas de Velocidad",
        params: { distancia: "20" },
      },
      {
        type: "rotar_nucleo",
        label: "ROTAR(90)",
        category: "action",
        hardwareRequired: "Botas de Velocidad",
        params: { grados: "90" },
      },
      {
        type: "iluminar",
        label: "ILUMINAR()",
        category: "action",
        hardwareRequired: "Faro Mágico",
        params: {},
      },
      {
        type: "abrir_puerta",
        label: "ABRIR_PUERTA()",
        category: "action",
        hardwareRequired: "Llave Antigua",
        params: {},
      },
      {
        type: "detectar_magia",
        label: "DETECTAR_MAGIA()",
        category: "action",
        hardwareRequired: "Espejo de Visión",
        params: {},
      },
      {
        type: "teletransportar",
        label: "TELETRANSPORTAR()",
        category: "action",
        hardwareRequired: "Portal de Teletransporte",
        params: {},
      },
      {
        type: "congelar",
        label: "CONGELAR()",
        category: "action",
        hardwareRequired: "Cristal de Escarcha",
        params: {},
      },
      {
        type: "si_distancia",
        label: "SI (distancia < 8)",
        category: "condition",
        hardwareRequired: "Sensor Ultrasónico",
        params: {},
      },
    ],
    hardware: [
      {
        id: "Cristal de Escarcha",
        name: "Cristal de Escarcha",
        icon: "ac_unit",
        color: "var(--primary)",
        bgClass: "bg-primary/20",
        textClass: "text-primary",
        borderClass: "border-primary/30",
        desc: "Congela puertas y enemigos con hielo mágico.",
        blocks: "[CONGELAR]",
        unlocks: ["congelar"],
      },
      {
        id: "Botas de Velocidad",
        name: "Botas de Velocidad",
        icon: "directions_run",
        color: "var(--success)",
        bgClass: "bg-success/20",
        textClass: "text-success",
        borderClass: "border-success/30",
        desc: "Desplazamiento sigiloso.",
        blocks: "[AVANZAR], [ROTAR]",
        unlocks: ["mover_ruedas", "rotar_nucleo"],
      },
      {
        id: "Faro Mágico",
        name: "Faro Mágico",
        icon: "highlight",
        color: "var(--accent)",
        bgClass: "bg-accent/20",
        textClass: "text-accent",
        borderClass: "border-accent/30",
        desc: "Ilumina pasadizos oscuros.",
        blocks: "[ILUMINAR]",
        unlocks: ["iluminar"],
      },
      {
        id: "Llave Antigua",
        name: "Llave Antigua",
        icon: "vpn_key",
        color: MAZE_COLORS.primary,
        bgClass: "bg-primary/20",
        textClass: "text-primary",
        borderClass: "border-primary/30",
        desc: "Abre puertas encantadas.",
        blocks: "[ABRIR_PUERTA]",
        unlocks: ["abrir_puerta"],
      },
      {
        id: "Espejo de Visión",
        name: "Espejo de Visión",
        icon: "visibility",
        color: "var(--primary)",
        bgClass: "bg-primary/20",
        textClass: "text-primary",
        borderClass: "border-primary/30",
        desc: "Revela rastros de magia.",
        blocks: "[DETECTAR_MAGIA]",
        unlocks: ["detectar_magia"],
      },
      {
        id: "Portal de Teletransporte",
        name: "Portal Mágico",
        icon: "swipe",
        color: "var(--accent)",
        bgClass: "bg-accent/20",
        textClass: "text-accent",
        borderClass: "border-accent/30",
        desc: "Teletransportación entre nodos.",
        blocks: "[TELETRANSPORTAR]",
        unlocks: ["teletransportar"],
      },
      {
        id: "Sensor Ultrasónico",
        name: "Sensor Mágico",
        icon: "sensors",
        color: "var(--success)",
        bgClass: "bg-success/20",
        textClass: "text-success",
        borderClass: "border-success/30",
        desc: "Detección de paredes cercanas.",
        blocks: "[SI_DISTANCIA]",
        unlocks: ["si_distancia"],
      },
    ],
    missions: [
      { id: "m1", title: "Encender el Faro", objective: "Equipa Botas y Faro. Avanza y usa [ILUMINAR].", maxBlocks: 2 },
      { id: "m2", title: "Primera Puerta", objective: "Navega hasta la puerta y usa [ABRIR_PUERTA] para abrirla.", maxBlocks: 4 },
      { id: "m3", title: "Rastro Mágico", objective: "Usa [DETECTAR_MAGIA] para encontrar el camino correcto.", maxBlocks: 3 },
      { id: "m4", title: "Atajo Dimensional", objective: "Llega al portal y usa [TELETRANSPORTAR] para cruzar.", maxBlocks: 5 },
      { id: "m5", title: "Escape del Laberinto", objective: "Combina iluminación, detección y puertas para escapar.", maxBlocks: 7 },
    ],
    defaultHardware: ["Botas de Velocidad"],
  },

  obstacle: {
    id: "obstacle",
    name: "Carrera de Obstáculos",
    description: "Pista de alta velocidad. Acelera, salta y esquiva para llegar a la meta.",
    icon: "speed",
    portSlots: [
      { id: "ps_race_wheels", name: "Puerto de Ruedas", label: "Ruedas de Carrera", icon: "settings_motion_mode", accepts: ["Ruedas de Carrera"] },
      { id: "ps_race_turbo", name: "Puerto de Turbo", label: "Turbo Compresor", icon: "bolt", accepts: ["Turbo Compresor"] },
      { id: "ps_race_suspension", name: "Puerto de Suspensión", label: "Suspensión Deportiva", icon: "swap_vertical_circle", accepts: ["Suspensión Deportiva"] },
      { id: "ps_race_spoiler", name: "Puerto de Alerones", label: "Alerones Activos", icon: "air", accepts: ["Alerones Activos"] },
      { id: "ps_race_sensor", name: "Puerto Sensor", label: "Sensor de Velocidad", icon: "speed", accepts: ["Sensor de Velocidad"] },
      { id: "ps_race_parachute", name: "Puerto de Paracaídas", label: "Paracaídas de Frenado", icon: "parachuting", accepts: ["Paracaídas de Frenado"] },
    ],
    blocks: [
      {
        type: "al_iniciar_sistema",
        label: "AL_INICIAR_SISTEMA",
        category: "event",
        params: {},
      },
      {
        type: "mover_ruedas",
        label: "AVANZAR(40)",
        category: "action",
        hardwareRequired: "Ruedas de Carrera",
        params: { distancia: "40" },
      },
      {
        type: "rotar_nucleo",
        label: "GIRAR(45)",
        category: "action",
        hardwareRequired: "Ruedas de Carrera",
        params: { grados: "45" },
      },
      {
        type: "acelerar",
        label: "ACELERAR(50)",
        category: "action",
        hardwareRequired: "Turbo Compresor",
        params: { velocidad: "50" },
      },
      {
        type: "frenar",
        label: "FRENAR()",
        category: "action",
        hardwareRequired: "Suspensión Deportiva",
        params: {},
      },
      {
        type: "saltar",
        label: "SALTAR()",
        category: "action",
        hardwareRequired: "Suspensión Deportiva",
        params: {},
      },
      {
        type: "esquivar",
        label: "ESQUIVAR()",
        category: "action",
        hardwareRequired: "Alerones Activos",
        params: {},
      },
      {
        type: "frenado_emergencia",
        label: "FRENADO_EMERGENCIA()",
        category: "action",
        hardwareRequired: "Paracaídas de Frenado",
        params: {},
      },
      {
        type: "si_distancia",
        label: "SI (distancia < 12)",
        category: "condition",
        hardwareRequired: "Sensor de Velocidad",
        params: {},
      },
    ],
    hardware: [
      {
        id: "Paracaídas de Frenado",
        name: "Paracaídas de Frenado",
        icon: "parachuting",
        color: "var(--danger)",
        bgClass: "bg-danger/20",
        textClass: "text-danger",
        borderClass: "border-danger/30",
        desc: "Despliega un paracaídas para frenar en seco.",
        blocks: "[FRENADO_EMERGENCIA]",
        unlocks: ["frenado_emergencia"],
      },
      {
        id: "Ruedas de Carrera",
        name: "Ruedas de Carrera",
        icon: "settings_motion_mode",
        color: "var(--success)",
        bgClass: "bg-success/20",
        textClass: "text-success",
        borderClass: "border-success/30",
        desc: "Neumáticos de alto rendimiento.",
        blocks: "[AVANZAR], [GIRAR]",
        unlocks: ["mover_ruedas", "rotar_nucleo"],
      },
      {
        id: "Turbo Compresor",
        name: "Turbo Compresor",
        icon: "bolt",
        color: RACE_COLORS.primary,
        bgClass: "bg-accent/20",
        textClass: "text-accent",
        borderClass: "border-accent/30",
        desc: "Aumento de velocidad repentino.",
        blocks: "[ACELERAR]",
        unlocks: ["acelerar"],
      },
      {
        id: "Suspensión Deportiva",
        name: "Suspensión Deportiva",
        icon: "swap_vertical_circle",
        color: "var(--primary)",
        bgClass: "bg-primary/20",
        textClass: "text-primary",
        borderClass: "border-primary/30",
        desc: "Amortiguación para saltos y frenado.",
        blocks: "[SALTAR], [FRENAR]",
        unlocks: ["saltar", "frenar"],
      },
      {
        id: "Alerones Activos",
        name: "Alerones Activos",
        icon: "air",
        color: "var(--accent)",
        bgClass: "bg-accent/20",
        textClass: "text-accent",
        borderClass: "border-accent/30",
        desc: "Estabilidad en curvas cerradas.",
        blocks: "[ESQUIVAR]",
        unlocks: ["esquivar"],
      },
      {
        id: "Sensor de Velocidad",
        name: "Sensor de Velocidad",
        icon: "speed",
        color: "var(--primary)",
        bgClass: "bg-primary/20",
        textClass: "text-primary",
        borderClass: "border-primary/30",
        desc: "Mide distancia a obstáculos en carrera.",
        blocks: "[SI_DISTANCIA]",
        unlocks: ["si_distancia"],
      },
    ],
    missions: [
      { id: "o1", title: "Puesta a Punto", objective: "Equipa Ruedas de Carrera y Suspensión Deportiva.", maxBlocks: 0 },
      { id: "o2", title: "Curva Cerrada", objective: "Avanza y usa [GIRAR] para tomar la primera curva.", maxBlocks: 2 },
      { id: "o3", title: "Salto Mortal", objective: "Acelera y usa [SALTAR] para superar la rampa.", maxBlocks: 3 },
      { id: "o4", title: "Eslalon", objective: "Combina giros y [ESQUIVAR] para pasar los conos.", maxBlocks: 5 },
      { id: "o5", title: "Gran Premio", objective: "Llega a la meta usando aceleración, saltos y esquivas.", maxBlocks: 7 },
    ],
    defaultHardware: ["Ruedas de Carrera"],
  },
};
