spring:

  application:
    name: PipreBackend

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/pipre_database}
    username: ${POSTGRES_USER:pipre_user}
    password: ${POSTGRES_PASSWORD:pipre_password}
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 3000
      maximum-pool-size: 30

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
external:
  fast-api:
    url: ${FAST_API_URL:http://dev-ml-ia:8000}
