export const AI_ENDPOINTS = {
  RIA01_PREDICT: "/ria01/predict",
  RIA03_RECOMMEND: "/ria03/recommend",
  RIA04_DIFFICULTY: "/ria04/difficulty",
  RIA08_ANOMALY: "/ria08/anomaly",
  RIA11_TIME: "/ria11/time",
  RIA01_INFO: "/ria01/info",
  RIA03_INFO: "/ria03/info",
  RIA04_INFO: "/ria04/info",
  RIA08_INFO: "/ria08/info",
  RIA11_INFO: "/ria11/info",
  HEALTH: "/health",
  CODE_FEEDBACK_ANALYZE: "/code-feedback/analyze",
  RIA12_PSEINT: "/ria12/pseint",
  FEATURES_AGGREGATE_STUDENT: (id: string) => `/features/aggregate/student/${id}`,
  FEATURES_AGGREGATE_GROUP: (id: string) => `/features/aggregate/group/${id}`,
};
